language: go
sudo: required
cache:
  directories:
  - "$HOME/gopath"
  - "$HOME/.cache/go-build"
before_cache:
- cd; rm -rf $TRAVIS_BUILD_DIR
go:
- 1.12.4
before_install:
- "./scripts/before_script.sh"
script:
- "./scripts/lint_and_test.sh"
