language: go
sudo: required
cache:
  directories:
  - "$HOME/gopath"
  - "$HOME/.cache/go-build"
before_cache:
- cd; rm -rf $TRAVIS_BUILD_DIR
go:
- 1.12.4
before_install:
- "./scripts/before_script.sh"
script:
- "./scripts/lint_and_test.sh"
notifications:
  slack:
    secure: IZ1RMOdxjfJoZhS3bLPk4180RjeN4+Us9aQjpFwkssov4zc9kuQE/7+GLd0w2hx8hJdTAIvPV2UXJA6fgffsN3fmufJuCoseA70jgJvjEa28y8uBNdkrux/E9bSHtgqhCoGlQWywEA9PngQ5WLitGB8f6hdo16thVc45eigD+Q7agKPq0lqqZ0jb/URQfn9UdQY69CSWHbdPcangJ08FLGiWL7m2w+9PqKKDdjw7awY1b9oi3IT13jQzZBFZ1geBomztoXTO9traVawlxWX+ccgbL2FurPs6QKl6RZj+8RM2h1E3o6vCu10sJ8WEZv8O6pHhyGcKuH2a/Buyi7eQX94TYd2W4cq1l1PDN8eEODgyEax9Sj0/JRltLubrl9nSEHlbo1QgYi3PbUa3AJ+1Vf0x59oOniTib+T2yKEYEHP/qu43MNbcqd5pD2Woq+INFihMZxLsCWk39crDblRXvxcvvsiZVwZF14vK6Wu3L0+sfqO0Z9gHIiMGy6XRdjDeFIkl84Mpmdv9OU35QR4YLFRBhtsRzoBic26DKRF+4L5Z/EoDrffmedXYm5yuJeZA9g6iMJVwz+edTPjkWj/n78dP914HgEcrE7281xykn107IYGHFWQxhqAlP0ErvVChKhDl5flcDZhrmwOV8UPQ83F7ayegZMSyBiEdrwLi0mo=
  on_success: change
  on_failure: always
  on_pull_requests: false
