version: "3.7"
services:
  chain:
    build: .
    environment:
      EVENTBRITE_AUTH: HPH2Q3QWLVB6K4BQSND3
      EVENTBRITE_EVENT: 74857698391
    ports:
      - 1317:1317
      - 1337:1337
      - 26657:26657
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
