version: "3.7"
services:
  chain:
    build: .
    environment:
      EVENTBRITE_AUTH: HPH2Q3QWLVB6K4BQSND3
      EVENTBRITE_EVENT: 74857698391
      AWS_ACCESS_KEY_ID: ignored
      AWS_SECRET_ACCESS_KEY: ignored
      AWS_REGION: "us-west-2"
      CHAIN_INIT: "init"
    ports:
      - 1317:1317
      - 1337:1337
      - 26657:26657
    volumes:
      - daemon:/root/.lyd
      - cli:/root/.lycli
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_SERVICES=s3,dynamodb
      - DATA_DIR=/tmp/localstack/data
volumes:
  daemon:
  cli:
